spring:
  application:
    name: blog-mainapp-service
  datasource:
    url: jdbc:mysql://localhost:3306/blogger?useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: "8082"
eureka:
  instance:
    hostname: localhost
  client: # Not a client, don't register with yourself (unless running
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
    # multiple discovery servers for redundancy)
  #    registerWithEureka: false
  #    fetchRegistry: false
  dashboard:
    enabled: true
    path: /dashboard